
services:
  tauri_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot_ui
    tty: true
    privileged: true
    network_mode: host
    working_dir: /root/
    environment:
      - ROS_DOMAIN_ID=0
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=${DISPLAY}
    volumes:
      - ./:/root/
      - ~/.ccache:/root/.ccache
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

